### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by dujeonglee** [dujeonglee/NetworkCodingRev#6]
#0  0x0807d930 in AVLTreeElement<NetworkCoding::DataTypes::SessionKey, NetworkCoding::ReceptionSession*>::~AVLTreeElement (this=0x80bfba0, __in_chrg=<optimized out>)
    at ../basiclibrary/avltree/AVLTree.h:207
#1  0x0807b685 in AVLTree<NetworkCoding::DataTypes::SessionKey, NetworkCoding::ReceptionSession*>::Clear (this=0x80c0764) at ../basiclibrary/avltree/AVLTree.h:918
#2  0x0807838d in NetworkCoding::Reception::~Reception (this=0x80c0760,
    __in_chrg=<optimized out>) at rx.cpp:761
#3  0x0804f5ac in NetworkCoding::NCSocket::~NCSocket (this=0x80bfba0,
    __in_chrg=<optimized out>) at ncsocket.h:257
#4  0x0804df78 in FreeSocket (handle=0x80bfba0) at api.cpp:61
#5  0x0804a77e in AsyncReceiveFunction (port=0xbffff8c4 "10000") at main.cpp:157
#6  0x0804a908 in main (argc=3, argv=0xbffff764) at main.cpp:172

#0  0x0807b66f in AVLTree<NetworkCoding::DataTypes::SessionKey, NetworkCoding::ReceptionSession*>::Clear (this=0x80c0764) at ../basiclibrary/avltree/AVLTree.h:917
#1  0x0807838d in NetworkCoding::Reception::~Reception (this=0x80c0760,
    __in_chrg=<optimized out>) at rx.cpp:761
#2  0x0804f5ac in NetworkCoding::NCSocket::~NCSocket (this=0x80bfba0,
    __in_chrg=<optimized out>) at ncsocket.h:257
#3  0x0804df78 in FreeSocket (handle=0x80bfba0) at api.cpp:61
#4  0x0804a77e in AsyncReceiveFunction (port=0xbffff8c4 "10000") at main.cpp:157
#5  0x0804a908 in main (argc=3, argv=0xbffff764) at main.cpp:172

**Comment by dujeonglee** [comment]
The following commit on AVLTree fix the problem.
https://github.com/dujeonglee/basiclibrary/commit/b1146b39733a98de51cf41ba50a3a8fa0c63feac
